language: php

php:
  - 5.5
  - 5.4
  - 5.3
  - hhvm

before_script:
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar install
  - chmod -R 777 test/rg/injektor/_factories/

script: phpunit
