language: php

sudo: false

cache:
    directories:
      - $HOME/.composer/cache/files

php:
  - 5.6
  - 5.5
  - 7.0
  - nightly
  - hhvm

before_script:
  - phpenv config-rm xdebug.ini

install:
  - composer install
  - chmod -R 0777 test/rg/injektor/_factories/
