language: php

sudo: false

cache:
    directories:
      - $HOME/.composer/cache/files

php:
  - 5.6
  - 5.5
  - 5.4
  - 7.0
  - nightly
  - hhvm

install:
  - composer install
  - chmod -R 0777 test/rg/injektor/_factories/

matrix:
  allow_failures:
    - php: nightly
    - php: 7.0
